disabled_rules: # rule identifiers turned on by default to exclude from running
  # rules I may want to turn on again
  - cyclomatic_complexity
  - force_cast
  - identifier_name
  - legacy_constructor
  - reduce_boolean
  - syntactic_sugar
  - unused_enumerated

  # rules I have no intention of every enabling
  - file_length
  - for_where
  - function_body_length
  - large_tuple
  - line_length
  - orphaned_doc_comment
  - type_body_length

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - capture_variable

type_name:
  allowed_symbols: ["_"] # these are allowed in type names

reporter: "xcode"

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

# force_cast: warning # implicitly
# force_try:
#   severity: warning # explicitly
# line_length: 110
# type_body_length:
#   - 300 # warning
#   - 400 # error
# file_length:
#   warning: 500
#   error: 1200
# identifier_name:
#   min_length: # only min_length
#     error: 4 # only error
#   excluded: # excluded via string array
#     - id
#     - URL
#     - GlobalAPIKey
